### PR TITLE
Bump ESLint version to 2.13.1

### PR DESCRIPTION
**Pull request by BrianSipple**
In advance of [getting set for ESLint 3.x support](https://github.com/ember-cli/broccoli-lint-eslint/issues/40), this PR updates us to the last release for 2.x ([2.13.1](https://github.com/eslint/eslint/releases/tag/v2.13.1)) before we move future 2.x support onto a [branch outside of master](https://github.com/ember-cli/broccoli-lint-eslint/tree/2.x). 

There aren't any breaking changes since `2.10.0`, so this would just be a minor version bump before we start publishing 3.x releases.

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good, but this was already allowed within the range in the current release. Maybe we don't need to update at all?

**Comment by BrianSipple** [comment]
The current release specifies `"eslint": "^2.10.0",` as dependency, which I believe would only give us patches to `2.10.x`.

**Comment by rwjblue** [comment]
Nope. ^ allows all numbers to change except the first non-zero one. In this case any of 2.x will be allowed. 

Checkout https://semver.npmjs.com for a really need way to play with what is allowed given various ranges.

**Comment by BrianSipple** [comment]
Ah, very true!

In either case, though, it _could_ be better to have the explicit version -- `~` vs `^` still trips me up occasionally 😄.

**Comment by rwjblue** [comment]
Ya, totally.  Wasn't trying to bikeshed at all. 😺

**Comment by Turbo87** [comment]
that would however prevent users from using a potential `2.13.2` if they ever did a critical bugfix for that branch again...

**Comment by BrianSipple** [comment]
@Turbo87 True, I could definitely change it to `^2.13.0`. In fact, I didn't intend to change the philosophy in the first place -- so that's a good catch.

**Comment by rwjblue** [comment]
Ya, we definitely do not want to lock this down like the PR does ATM.

**Comment by BrianSipple** [comment]
Updated.

**Pull request merged**
