### PR TITLE
Simplify Babel usage for running tests

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @BrianSipple @rwjblue

### CODE REVIEW

**Comment by alexlafroscia** [comment]
All looks good to me!

**Comment by rwjblue** [comment]
👍

**Comment by alexlafroscia** [comment]
Hmm, I see that this merged into 2.x.  Was the PR made against that branch?  Or did was that change by mistake in the merge?  I didn't do that intentionally...

**Comment by Turbo87** [comment]
My suggestion is merging the 2.x branch regularly into master like we do in ember-cli too. Since 2.x is still an active target I'd like to get those changes into both branches.

**Pull request merged**
